services:
  - type: web
    name: hotstar-clone
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn hotstar_clone.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
